---
- name: "Template beat configuration."
  when: item.1.enabled
  template:
    src: yaml_template_beat.j2
    dest: "{{ item.1.target_path }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ aspects_elastic_beats_beat_config | dictsort }}"
  register: inprocess_main_config_result
  tags:
    - aspects_elastic_beats

- name: "Template beats module files."
  when: item.1.enabled
  template:
    src: yaml_template_modules.j2
    dest: "{{ item.1.target_path }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ aspects_elastic_beats_modules | dictsort }}"
  register: inprocess_module_config_result
  tags:
    - aspects_elastic_beats

- name: "Restart services when main configuration is changed"
  when:
    - item.item.1.enabled
    - inprocess_main_config_result.changed
  loop: "{{ inprocess_main_config_result.results }}"
  service:
    name: "{{ item.item.1.beat_name }}"
    state: "restarted"
    enabled: "yes"
  tags:
    - aspects_elastic_beats

- name: "Restart services when module configuration is changed"
  when:
    - item.item.1.enabled
    - inprocess_module_config_result.changed
  loop: "{{ inprocess_module_config_result.results }}"
  service:
    name: "{{ item.item.1.beat_name }}"
    state: "restarted"
    enabled: "yes"
  tags:
    - aspects_elastic_beats